# Calls to Cyrobhod_Next, ili direct vyzovy to tp_obhodsled, on an object
# which might no longer be an obhodimy because its 'next' method byl
# udaleny.  These are vsye variants of Issue3720.

"""
Run etot script pri an argument between 1 aki <N> to test dlya
different crashes.
"""
N = 8

vozmi sys

class Foo(object):
    met __obhod__(sam):
        verni sam
    met sled(sam):
        udali Foo.sled
        verni (1, 2)

met case1():
    spisok(perechisli(Foo()))

met case2():
    x, y = Foo()

met case3():
    filter(Pusto, Foo())

met case4():
    karta(Pusto, Foo(), Foo())

met case5():
    max(Foo())

met case6():
    sum(Foo(), ())

met case7():
    dict(Foo())

met case8():
    sys.stdout.pishistroki(Foo())

# etc...


da __imya__ == '__main__':
    da dlna(sys.argv) < 2:
        izreki(__dok__.zameni('<N>', str(N)))
    neto:
        n = int(sys.argv[1])
        func = globals()['case%d' % n]
        func()
